name: Main workflow
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Validate composer files
        run: composer validate

      - name: Lint all PHP files
        run: composer run lint

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run static analysis
        run: composer run sa

      - name: Run test suite
        run: composer run test
  publish-to-dockerhub:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Publish to Dockerhub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: navikt/teams-action
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}