name: Test and publish
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Validate composer files
        run: composer validate

      - name: Lint all PHP files
        run: composer run lint

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@preview
        with:
          path: vendor
          key: ${{ runner.os }}-node-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest --no-ansi

      - name: Run static analysis
        run: composer run sa

      - name: Run test suite
        run: composer run test
  publish-to-dockerhub:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Publish to Dockerhub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: navikt/teams-action
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}